[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd frontend && npm install --legacy-peer-deps && npm run build && cd .. && npm run seed"

[deploy]
startCommand = "npm run start-prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 45
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[deploy.env]
NODE_ENV = "production"
PORT = "8080"
DATABASE_URL = "${DATABASE_URL}"
SKIP_DB_INIT = "false"
LOG_LEVEL = "debug"
VITE_API_URL = "https://web-production-310c4.up.railway.app/api"

# Railway automatycznie dostarczy wszystkie potrzebne zmienne środowiskowe dla bazy danych 