[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm run start-prod"
healthcheckPath = "/zdrowie"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[deploy.env]
NODE_ENV = "production"
PORT = "3000"
DATABASE_URL = "${DATABASE_URL}"

# Railway automatycznie dostarczy wszystkie potrzebne zmienne środowiskowe dla bazy danych 