[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "node server.js"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[[services]]
  [services.variables]
    NODE_ENV = "production"
    PORT = "3000" 