[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm run start-prod"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[deploy.env]
NODE_ENV = "production"
PORT = "8080"
DATABASE_URL = "${DATABASE_URL}"
SKIP_DB_INIT = "false"

# Railway automatycznie dostarczy wszystkie potrzebne zmienne środowiskowe dla bazy danych 