[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/zdrowie"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[deploy.env]
NODE_ENV = "production"
PORT = "3000"

# Konfiguracja bazy danych jest dostarczana automatycznie przez Railway
# poprzez zmienne PGHOST, PGPORT, PGDATABASE, PGUSER, PGPASSWORD 